name: Labels
on:
  pull_request:
    types: [labeled]

jobs:
  check-labels:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        id: checklabels
        run: |
          LABELS=$(echo "${{ join(github.event.pull_request.labels.*.name, ',') }}")
          echo "$LABELS"
          if [[ $LABELS == *'rc'* ]]; then
            echo "::set-output name=contains-rc::true"
          else
            echo "::set-output name=contains-rc::false"
          fi

      - name: Echo label result
        run: |
          contains_rc=${{ steps.checklabels.outputs.contains-rc }}
          if [[ "$contains_rc" == "true" ]]; then
            pr_text="This is the PR (RC) !"
          else
            pr_text="This is the PR !"
          fi
          echo "$pr_text"
