name: Labels
on:
  pull_request:
    types: [labeled]

jobs:
  check-labels:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        id: checklabels
        run: |
          LABELS=$(echo "${{ join(github.event.pull_request.labels.*.name, ',') }}")
          echo "$LABELS"
          if [[ $LABELS == *'rc'* ]]; then
            pr_text="SLT Needed :test_tube: (TO-RC)"
          else
            pr_text="SLT Needed :test_tube:"
          fi
          echo "title=$pr_text" >> $GITHUB_OUTPUT

      - name: Echo label result
        env:
          TITLE: ${{ steps.checklabels.outputs.title }}
        run: |
          echo "$TITLE"
